services:
  db:
    image: postgres:16
    container_name: bd3_postgres
    environment:
      POSTGRES_DB: tienda
      POSTGRES_USER: alumno
      POSTGRES_PASSWORD: alumno
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - bd3_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alumno -d tienda"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  bd3_pgdata:
